# Generated by Django 5.1.6 on 2025-02-09 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('ready', 'Готов'), ('paid', 'Оплачено')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Номер стола'),
        ),
    ]
